runtime: java
env: flex
runtime_config:
   jdk: openjdk8
env_variables:
  RD_SQL_PASSWORD: Superpck123
  STRIPE_SECRET_KEY: sk_test_51IrOE7IKHZePqhnOAJKub4w1t7lPuDK0uNYzVmcctHup9VxzlC7UHIX4RQtJOBSpyRIQdN1F7k6GS7c73PopxPdZ008zKoSnAL
  STRIPE_PUBLISHABLE_KEY: pk_test_51IrOE7IKHZePqhnO0RSRGcGLWIEo1DJKFKLWhkyqaio52VqzPlqteYycIDtrL50q1qRAstObuZGMstGa4OULQdZQ00QB0MZHa1
  DOMAIN: http://localhost:3000
  PAYMENT_METHOD_TYPES: card
  PRICE: price_1IrQwuIKHZePqhnOxm90ekE4
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8